var async = require("async");
var AWS = require("aws-sdk");
var gm = require("gm").subClass({imageMagick: true});
var fs = require("fs");
var mktemp = require("mktemp");

var THUMB_WIDTH = 100,
    THUMB_HEIGHT = 100,
    LARGE_WIDTH = 2000,
    LARGE_HEIGHT = 2000,
    ALLOWED_FILETYPES = ['png', 'jpg', 'jpeg', 'bmp', 'tiff', 'pdf', 'gif'];

var utils = {
  decodeKey: function(key) {
    return decodeURIComponent(key).replace(/\+/g, ' ');
  }
};


var s3 = new AWS.S3();


exports.handler = function(event, context) {
  console.log(event);
  var bucket = event.Records[0].s3.bucket.name,
  srcKey = utils.decodeKey(event.Records[0].s3.object.key),
  dstKey = srcKey.replace(/\.\w+$/, ".png"),
  fileType = srcKey.match(/\.\w+$/);

  if (fileType === null) {
    console.error("Invalid filetype found for key: " + srcKey);
    return;
  }

  fileType = fileType[0].substr(1);

  if (ALLOWED_FILETYPES.indexOf(fileType) === -1 || srcKey.includes("lambda_thumbnail_small.png")
    || srcKey.includes("lambda_thumbnail_large.png") || srcKey.includes("lambda_thumbnail_orig.png")) {
    console.error("Filetype " + fileType + " not valid for thumbnail, exiting");
    return;
  }
  
  var filetypeIndex = dstKey.indexOf(".png");
  dstKey = dstKey.substring(0, filetypeIndex) + "_lambda_thumbnail_small.png";
  var dstKey2 = dstKey.substring(0, filetypeIndex) + "_lambda_thumbnail_large.png";
  var dstKey3 = dstKey.substring(0, filetypeIndex) + "_lambda_thumbnail_orig.png";

  if(fileType.includes("pdf")) {
    async.waterfall([

    function download(next) {
        //Download the image from S3
        s3.getObject({
          Bucket: bucket,
          Key: srcKey
        }, next);
      },
      
      function stop(response, next) {
        console.log(response.Metadata);
        if('lamdbacreation' in response.Metadata) {
          next("This file was generated by image_resize lamdba");
        } else {
          next(null, response);
        }
      },

      function createThumbnail(response, next) {
        var temp_file, image;
        console.log(response);
        if(fileType === "pdf") {
          temp_file = mktemp.createFileSync("/tmp/XXXXXXXXXX.pdf")
          fs.writeFileSync(temp_file, response.Body);
          image = gm(temp_file + "[0]");
        } else if (fileType === 'gif') {
          temp_file = mktemp.createFileSync("/tmp/XXXXXXXXXX.gif")
          fs.writeFileSync(temp_file, response.Body);
          image = gm(temp_file + "[0]");
        } else {
          image = gm(response.Body);
        }

        image.size(function(err, size) {
          var scalingFactor = 1,
          width = scalingFactor * size.width,
          height = scalingFactor * size.height;

          this.resize(width, height)
          .toBuffer("png", function(err, buffer) {
            if(temp_file) {
              fs.unlinkSync(temp_file);
            }

            if (err) {
              next(err);
            } else {
              next(null, response.contentType, buffer);
            }
          });
        });
      },

      function uploadThumbnail(contentType, data, next) {
        s3.putObject({
          Bucket: bucket,
          Key: dstKey3,
          Body: data,
          ContentType: "image/png",
          ACL: 'public-read',
          Metadata: {
            lamdbacreation: 'TRUE'
          }
        }, next);
      }

      ],
      function(err) {
        if (err) {
          console.error(
            "Unable to generate thumbnail for '" + bucket + "/" + srcKey + "'" +
            " due to error: " + err
            );
        } else {
          console.log("Created thumbnail for '" + bucket + "/" + srcKey + "'");
        }

        context.done();
      });
  }

  async.waterfall([

    function download(next) {
        //Download the image from S3
        s3.getObject({
          Bucket: bucket,
          Key: srcKey
        }, next);
      },
      
      function stop(response, next) {
        console.log(response.Metadata);
        if('lamdbacreation' in response.Metadata) {
          next("This file was generated by image_resize lamdba");
        } else {
          next(null, response);
        }
      },

      function createThumbnail(response, next) {
        var temp_file, image;
        console.log(response);
        if(fileType === "pdf") {
          temp_file = mktemp.createFileSync("/tmp/XXXXXXXXXX.pdf")
          fs.writeFileSync(temp_file, response.Body);
          image = gm(temp_file + "[0]");
        } else if (fileType === 'gif') {
          temp_file = mktemp.createFileSync("/tmp/XXXXXXXXXX.gif")
          fs.writeFileSync(temp_file, response.Body);
          image = gm(temp_file + "[0]");
        } else {
          image = gm(response.Body);
        }

        image.size(function(err, size) {
          var scalingFactor = Math.min(1, THUMB_WIDTH / size.width, THUMB_HEIGHT / size.height),
          width = scalingFactor * size.width,
          height = scalingFactor * size.height;

          this.resize(width, height)
          .toBuffer("png", function(err, buffer) {
            if(temp_file) {
              fs.unlinkSync(temp_file);
            }

            if (err) {
              next(err);
            } else {
              next(null, response.contentType, buffer);
            }
          });
        });
      },

      function uploadThumbnail(contentType, data, next) {
        s3.putObject({
          Bucket: bucket,
          Key: dstKey,
          Body: data,
          ContentType: "image/png",
          ACL: 'public-read',
          Metadata: {
            lamdbacreation: 'TRUE'
          }
        }, next);
      }

      ],
      function(err) {
        if (err) {
          console.error(
            "Unable to generate thumbnail for '" + bucket + "/" + srcKey + "'" +
            " due to error: " + err
            );
        } else {
          console.log("Created thumbnail for '" + bucket + "/" + srcKey + "'");
        }

        context.done();
      });
      
  async.waterfall([

    function download(next) {
        //Download the image from S3
        s3.getObject({
          Bucket: bucket,
          Key: srcKey
        }, next);
      },
      
      function stop(response, next) {
        console.log(response.Metadata);
        if('lamdbacreation' in response.Metadata) {
          next("This file was generated by image_resize lamdba");
        } else {
          next(null, response);
        }
      },

      function createThumbnail(response, next) {
        var temp_file, image;
        console.log(response);
        if(fileType === "pdf") {
          temp_file = mktemp.createFileSync("/tmp/XXXXXXXXXX.pdf")
          fs.writeFileSync(temp_file, response.Body);
          image = gm(temp_file + "[0]");
        } else if (fileType === 'gif') {
          temp_file = mktemp.createFileSync("/tmp/XXXXXXXXXX.gif")
          fs.writeFileSync(temp_file, response.Body);
          image = gm(temp_file + "[0]");
        } else {
          image = gm(response.Body);
        }

        image.size(function(err, size) {
          var scalingFactor = Math.min(1, LARGE_WIDTH / size.width, LARGE_HEIGHT / size.height),
          width = scalingFactor * size.width,
          height = scalingFactor * size.height;

          this.resize(width, height)
          .toBuffer("png", function(err, buffer) {
            if(temp_file) {
              fs.unlinkSync(temp_file);
            }

            if (err) {
              next(err);
            } else {
              next(null, response.contentType, buffer);
            }
          });
        });
      },

      function uploadThumbnail(contentType, data, next) {
        s3.putObject({
          Bucket: bucket,
          Key: dstKey2,
          Body: data,
          ContentType: "image/png",
          ACL: 'public-read',
          Metadata: {
            lamdbacreation: 'TRUE'
          }
        }, next);
      }

      ],
      function(err) {
        if (err) {
          console.error(
            "Unable to generate thumbnail for '" + bucket + "/" + srcKey + "'" +
            " due to error: " + err
            );
        } else {
          console.log("Created thumbnail for '" + bucket + "/" + srcKey + "'");
        }

        context.done();
      });
};
